export const questionList = {
    0: "Do you see more green or more yellow numbers?",
    1: "On how many racks is the sum of the numbers 18 or more?",
    2: "On how many racks is the sum of the numbers 12 or more?",
    3: "On how many racks can you see the same number but in different colors (e.g., a blue 7 and a yellow 7 on one rack)?",
    4: "On how many racks can you see 3 different colors?",
    5: "On how many racks do you see only even or uneven numbers?",
    6: "On how many racks do you see at least 2 numbers that are exactly the same (the same number and the same color)?",
    7: "On how many racks do you see three consecutive numbers?",
    8: "How many colors can you see?",
    9: "How many colors can you see at least 3 times?",
    10: "How many numbers do you not see at all?",
    11: "How many of the following numbers can you see in total: green one, black five, pink seven?",
    12: "Do you see more threes or more pink sixes?",
    13: "Do you see more green sixes or more yellow sevens?",
    14: "Do you see more yellow twos or more yellow sevens?",
    15: "Do you see more pink sixes or more green sixes?",
    16: "Do you see more blue sevens or more sevens of a different color [combined]?",
    17: "Do you see more brown or more blue numbers? ",
    18: "Do you see more red or more pink numbers? ",
    19: "Do you see more green or more blue numbers?",
    20: "Do you see more yellow or more pink numbers?",
    21: "Do you see more black or more brown numbers? ",
    22: "Do you see more black or more red numbers?",
}