export const questionList = {
    Q0: "Do you see more green or more yellow numbers?",
    Q1: "On how many racks is the sum of the numbers 18 or more?",
    Q2: "On how many racks is the sum of the numbers 12 or more?",
    Q3: "On how many racks can you see the same number but in different colors (e.g., a blue 7 and a yellow 7 on one rack)?",
    Q4: "On how many racks can you see 3 different colors?",
    Q5: "On how many racks do you see only even or uneven numbers?",
    Q6: "On how many racks do you see at least 2 numbers that are exactly the same (the same number and the same color)?",
    Q7: "On how many racks do you see three consecutive numbers?",
    Q8: "How many colors can you see?",
    Q9: "How many colors can you see at least 3 times?",
    Q10: "How many numbers do you not see at all?",
    Q11: "How many of the following numbers can you see in total: green one, black five, pink seven?",
    Q12: "Do you see more threes or more pink sixes?",
    Q13: "Do you see more green sixes or more yellow sevens?",
    Q14: "Do you see more yellow twos or more yellow sevens?",
    Q15: "Do you see more pink sixes or more green sixes?",
    Q16: "Do you see more blue sevens or more sevens of a different color [combined]?",
    Q17: "Do you see more brown or more blue numbers? ",
    Q18: "Do you see more red or more pink numbers? ",
    Q19: "Do you see more green or more blue numbers?",
    Q20: "Do you see more yellow or more pink numbers?",
    Q21: "Do you see more black or more brown numbers? ",
    Q22: "Do you see more black or more red numbers?",
}