export const questionList = {
    0: "Do you see more green or more yellow numbers?",
    1: "On how many racks is the sum of the numbers 18 or more?",
    2: "On how many racks is the sum of the numbers 12 or more?",
    3: "On how many racks can you see the same number but in different colors (e.g., a blue 7 and a yellow 7 on one rack)?",
    4: "On how many racks can you see 3 different colors?",
    5: "On how many racks do you see only even or uneven numbers?",
    6: "On how many racks do you see at least 2 numbers that are exactly the same (the same number and the same color)?",
    7: "On how many racks do you see three consecutive numbers?",
    8: "How many colors can you see?",
    9: "How many colors can you see at least 3 times?",
    10: "How many numbers do you not see at all?",
    11: "How many of the following numbers can you see in total: green one, black five, pink seven?",
    12: "Do you see more threes or more pink sixes?",
    13: "Do you see more green sixes or more yellow sevens?",
    14: "Do you see more yellow twos or more yellow sevens?",
    15: "Do you see more pink sixes or more green sixes?",
    16: "Do you see more blue sevens or more sevens of a different color [combined]?",
    17: "Do you see more brown or more blue numbers? ",
    18: "Do you see more red or more pink numbers? ",
    19: "Do you see more green or more blue numbers?",
    20: "Do you see more yellow or more pink numbers?",
    21: "Do you see more black or more brown numbers? ",
    22: "Do you see more black or more red numbers?",
}

export const shortQuestionList = {
    0: 'More Green or Yellow?',
    1: "# Racks w/ Sum >= 18?",
    2: "# Racks w/ Sum >= 12?",
    3: "# Racks w/ Same number, different color?",
    4: "# Racks w/ 3 different colors?",
    5: "# Racks w/ only even or odd?",
    6: "# Racks w/ at least 2 cards that are the same?",
    7: "# Racks w/ consecutive numbers?",
    8: "# Colors visible?",
    9: "# Colors visible at least 3 times?",
    10: "# Numbers not visible?",
    11: "# of: Green 1, Black 5, Pink 7?",
    12: "More 3s or Pink 6s?",
    13: "More Green 6s or Yellow 7s?",
    14: "More Yellow 2s or Yellow 7s?",
    15: "More Pink 6s or Green 6s?",
    16: "More Blue 7s or Non-Blue 7s?",
    17: "More Brown or Blue?",
    18: "More Red or Pink?",
    19: "More Green or Blue?",
    20: "More Yellow or Pink?",
    21: "More Black or Brown?",
    22: "More Black or Red?",

}